#!/usr/bin/env node
// Generates ARTICLE-INDEX.md from news.js data.
// Run: node scripts/generate-index.mjs

import { articles, sourcePool, desks, authors } from '../src/data/news.js';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const sorted = [...articles].sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt));

const lines = [
  '# Article Index',
  '',
  `> Auto-generated by \`node scripts/generate-index.mjs\` — do not edit manually.`,
  '',
  `**${articles.length}** articles | **${sourcePool.length}** sources | **${desks.length}** desks`,
  '',
  `Date range: ${sorted[sorted.length - 1].publishedAt.slice(0, 10)} to ${sorted[0].publishedAt.slice(0, 10)}`,
  '',
  '## Articles by date (newest first)',
  '',
  '| Date | Slug | Desk | Tags |',
  '|------|------|------|------|'
];

for (const a of sorted) {
  const tags = a.tags.slice(0, 4).join(', ');
  lines.push(`| ${a.publishedAt.slice(0, 10)} | ${a.slug} | ${a.desk} | ${tags} |`);
}

lines.push('');
lines.push('## Desk summary');
lines.push('');
for (const d of desks) {
  const count = articles.filter(a => a.desk === d).length;
  lines.push(`- **${d}**: ${count} articles`);
}

lines.push('');
lines.push('## All tags');
lines.push('');
const tagCounts = {};
for (const a of articles) {
  for (const t of a.tags) {
    tagCounts[t] = (tagCounts[t] || 0) + 1;
  }
}
const sortedTags = Object.entries(tagCounts).sort((a, b) => b[1] - a[1]);
lines.push(sortedTags.map(([tag, count]) => `\`${tag}\` (${count})`).join(' · '));

lines.push('');
lines.push('## Source pool summary');
lines.push('');
lines.push(`${sourcePool.length} sources total. Last index: **${sourcePool.length - 1}** — append new sources starting at index **${sourcePool.length}**.`);
lines.push('');

const tierCounts = {};
for (const s of sourcePool) {
  tierCounts[s.tier] = (tierCounts[s.tier] || 0) + 1;
}
for (const [tier, count] of Object.entries(tierCounts).sort()) {
  lines.push(`- ${tier}: ${count} sources`);
}

const output = lines.join('\n') + '\n';
const outPath = join(root, 'ARTICLE-INDEX.md');
writeFileSync(outPath, output);
console.log(`Wrote ${outPath} (${articles.length} articles, ${sourcePool.length} sources)`);
